# Generated by Django 5.2.7 on 2025-11-24 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mai_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maihub',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maihub',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='mai_hub.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='maihub',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='mai_hub.tagpost', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='maihub',
            index=models.Index(fields=['-time_create'], name='mai_hub_mai_time_cr_5e125d_idx'),
        ),
    ]
